### ISSUE TITLE
OS Requirements

### ISSUE THREAD

**Issue by darox** [joelbarmettlerUZH/auto-tinder#9]
What are the OS requirements? Do I need a GPU or can I run the model on a CPU?

The main error I'm getting:

`Traceback (most recent call last):
  File "auto_tinder.py", line 138, in <module>
    detection_graph = person_detector.open_graph()
  File "/home/dario/dev/tinder/py37-venv/auto-tinder/person_detector.py", line 56, in open_graph
    od_graph_def = tf.GraphDef()
AttributeError: module 'tensorflow' has no attribute 'GraphDef'`

after already installing the tensorflow person detector api via:
`pip install tensorflow-object-detection-api`

**Comment by PFCid** [comment]
In my case I had the same problem because I was using Tensorflow 2, so I change the code as follows: 

tf.GraphDef() --> tf.compat.v1.GraphDef() 
tf.gfile.GFile() --> tf.compat.v2.io.gfile.GFile()
